# Generated by Django 2.2.6 on 2020-05-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Wallet',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
