# Generated by Django 2.2.6 on 2020-05-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200512_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
